# Generated by Django 5.2.4 on 2025-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('finished', 'Finished'), ('upcoming', 'Upcoming')], default='current', max_length=10),
        ),
    ]
