# Generated by Django 5.2.4 on 2025-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
