# Generated by Django 5.2.4 on 2025-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_client_alter_project_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number_of_storeys',
            field=models.IntegerField(default=1),
        ),
    ]
