version: '3.9'

services:
  web:
    image: ${DOCKER_USERNAME}/estimator:latest
    env_file: .env
    command: gunicorn estimator.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
