# Generated by Django 5.2.4 on 2025-07-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_materialcategory_material_category'),
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField()),
                ('quantity_procured', models.FloatField(default=0)),
                ('date_procured', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
