# Generated by Django 5.2.4 on 2025-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_procurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatecomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatecomponent',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='estimatecomponent',
            name='unit',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
