# Generated by Django 5.2.4 on 2025-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_estimatecomponent_description_estimatecomponent_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
