# Generated by Django 5.2.4 on 2025-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_materialcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatecomponent',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='estimatecomponent',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='standard',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
