# Generated by Django 5.2.4 on 2025-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0007_estimatecomponent_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
