# Generated by Django 5.2.4 on 2025-08-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0008_procurement_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date by which procurement must be completed.', null=True),
        ),
    ]
