name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Build & push image to Docker Hub
      - name: Build and push Docker image

        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/estimator:latest
          docker build --target prod -t $IMAGE .
          docker push $IMAGE

      # 3. SSH into EC2 and deploy
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/estimator || git clone https://github.com/${{ github.repository }} ~/estimator
            cd ~/estimator
            git pull origin main
            docker pull ${{ secrets.DOCKER_USERNAME }}/estimator:latest
            docker-compose down -v
            docker-compose up -d --build
            docker image prune -f